"""Add story fields to Product for craft storytelling

Revision ID: bd7b44d2db05
Revises: df4b377aafd7
Create Date: 2026-07-15 11:49:38.088086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd7b44d2db05'
down_revision = 'df4b377aafd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('story', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('artisan_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('origin_region', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('video_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('video_url')
        batch_op.drop_column('origin_region')
        batch_op.drop_column('artisan_message')
        batch_op.drop_column('story')

    # ### end Alembic commands ###
