"""Add experience, specialization, profile photo to ArtisanProfile

Revision ID: e3f8b574501f
Revises: bd7b44d2db05
Create Date: 2026-07-15 12:41:35.217199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3f8b574501f'
down_revision = 'bd7b44d2db05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artisan_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience_years', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('specialization', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('profile_photo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artisan_profiles', schema=None) as batch_op:
        batch_op.drop_column('profile_photo')
        batch_op.drop_column('specialization')
        batch_op.drop_column('experience_years')

    # ### end Alembic commands ###
