"""Add updated_at to OrderItem for delivery tracking

Revision ID: f42ffc02c6b6
Revises: 12db72f08cd6
Create Date: 2026-07-14 13:06:14.332334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f42ffc02c6b6'
down_revision = '12db72f08cd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
